version: '2.1'

services:

  server:
    image: back
    container_name: 'servergv77'
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/diplomgv77
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_URL: jdbc:mysql://database:3306/diplomgv77
      SPRING_LIQUIBASE_USER: root
      SPRING_LIQUIBASE_PASSWORD: root

  database:
    image: mysql
    container_name: 'database'
    volumes:
      - /mysql_data:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diplomgv77
    ports:
      - "3306:3306"